#!/usr/bin/env bash

# Check if nmap is installed
[ -z "$(which nmap)" ] && echo "nmap is not installed! Please install nmap first" && exit

# Get interface with Internet connection
intf=$(ip route get 1.1.1.1 | awk '{print $5}')
echo "Using $intf as interface..."

# Get IP of interface
intf_ip=$(ifconfig $intf | grep inet | sed -n 1p | awk '{print $2}')
echo "IP Address of $intf : $intf_ip"

# Get IP range of interface
cidr=$(ip route | grep $intf_ip | grep "$intf proto kernel" | awk '{print $1}')
echo "CIDR block : $cidr"

# Scan network for Raspberry Pi
scan_count=0
while [ -z "$pi" ]; do
 echo "SCAN #$scan_count"
 pi=$(sudo nmap -sS -p22 $cidr | grep -B 5 Raspberry | sed -n 1p | awk '{print $5}')
 [ -z "$pi" ] && echo "Pi not found. Scanning again..."  || echo "Raspberry Pi IP address : $pi"
 scan_count=$(expr $scan_count + 1)
done
